# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title:
  English: Nimf
  한국어: 님프
  中文: 宁芙
  日本語: ニンフ
email: cogniti@gmail.com
description:
  English: Copyright (c) 2015 - 2017 Hodong Kim
  한국어: 저작권 (c) 2015 - 2017 김호동
  中文: 版权所有 (c) 2015 - 2017 金豪东
  日本語: 著作権（c）2015 - 2017 キム・ホドン
index:
  English:
  한국어: ko/index.html
  中文: zh/index.html
  日本語: ja/index.html
feed:
  English: /feed.xml
  한국어: /ko/feed.xml
  中文: /zh/feed.html
  日本語: /ja/feed.html
baseurl: "/nimf" # the subpath of your site, e.g. /blog
url: "https://cogniti.github.io" # the base hostname & protocol for your site
#twitter_username: jekyllrb
github_username:  cogniti/nimf

# Build settings
markdown: kramdown
